name: Waka Readme

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_PROFILE_VIEWS : "False"
          SHOW_LANGUAGE_PER_REPO : "False"
          SHOW_LOC_CHART : "False"
          SHOW_SHORT_INFO : "False"
          SHOW_PROJECTS : "False"
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_TITLE : true
